<!--<script src="http://www.nal.usda.gov/sites/all/themes/gatag.js" type="text/javascript"></script>-->
<script type="text/JavaScript">
 var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-28627214-1']);
  _gaq.push(['_setDomainName', 'nal.usda.gov']);
  _gaq.push(['_setAllowLinker', true]);

  _gaq.push(['_trackPageview']);

  _gaq.push(['_setAccount', 'UA-466807-3']);
  _gaq.push(['_setDomainName', 'usda.gov']);
  _gaq.push(['_setAllowLinker', true]);
  _gaq.push(['_trackPageview']);

  _gaq.push(['a._setAccount', 'UA-27627304-18']);
  _gaq.push(['a._setDomainName', 'usda.gov']);
  _gaq.push(['a._setAllowLinker', true]);
  _gaq.push(['a._trackPageview']);

  _gaq.push(['b._setAccount', 'UA-27627304-1']);
  _gaq.push(['b._setDomainName', 'usda.gov']);
  _gaq.push(['b._setAllowLinker', true]);
  _gaq.push(['b._trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 
'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 
'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; 
s.parentNode.insertBefore(ga, s);
  })();

</script>

